export default Object.freeze({
  
    REGISTER_MALADE: 'Register_malade',
    WELCOME: 'Welcome',
    ROLE: 'Role',
    LOGIN2: 'Login2',
    PROBLEM: 'Problem',
    CONNECTION: 'Connection',
    CODE:'Code',
    PILULIER2:'Pilulier2 ,',
    HOME_PROCHE: 'Home_proche',
    HOME_MALADE: 'Home_malade',
    REGISTER_PROCHE: 'Register_proche',
    URGENCE1: 'Urgence1' ,
    URGENCE2: 'Urgence2'  ,
    URGENCE3 : 'Urgence3' ,
    URGENCE4 : 'Urgence4' ,
    SCAN: 'Scan_code',
    PILULIER1:'Pilulier1' ,
    PILULIER3:'Pilulier3' ,
    PILULIER4:'Pilulier4' ,
    RAPPELS1: 'Rappels1' ,
    TEST:'Test',
}) 