import { StyleSheet, Text, View, ScrollView } from 'react-native'
import React from 'react'

const Test = () => {
  return (
    <View>
      <ScrollView>
          <Text>
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
          </Text>
          <Text>
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
          </Text>
          <Text>
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
          </Text>
          <Text>
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
          </Text><Text>
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
          </Text><Text>
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
          </Text><Text>
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaaaaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
              aaaaaaaaa
          </Text>
      </ScrollView>
    </View>
  )
}

export default Test

const styles = StyleSheet.create({})